site_name: murpg
repo_url: https://github.com/rguillon/murpg
site_url: https://rguillon.github.io/murpg
site_description: Minimalist tabletop RPG rules system
site_author: Renaud Guillon
edit_uri: edit/main/docs/
repo_name: rguillon/murpg
copyright: Maintained by <a href="https://rguillon.com">rguillon</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/murpg"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rguillon/murpg
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/murpg

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
